apiVersion: apps/v1
kind: Deployment
metadata:
  name: frntEnd
  namespace: devolpment
spec:
  selector:
    matchLabels:
      app: frntEnd
  replicas: 1
  template:
    metadata:
      labels:
        app: frntEnd
    spec:
      containers:
      - name: frntEnd
        image:navedamanat/frntend:v4

        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frntEnd
  namespace: devolpment
spec:
  selector:
    app: frntEnd
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80

